=== hackxiyu/GoodManeger/db/good.dtd
<?xml version="1.0" encoding="GBK"?>
<!ELEMENT goods (good*)>
<!ELEMENT good (id,name,price)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== hackxiyu/GoodManeger/db/good.xml
<?xml version="1.0" encoding="GBK"?>
<!DOCTYPE goods SYSTEM "good.dtd">

<goods>
    <good>
        <id>3</id>
        <name>6</name>
        <price>6.0</price>
    </good>
    <good>
        <id>1</id>
        <name>1</name>
        <price>1.0</price>
    </good>
    <good>
        <id>2</id>
        <name>2</name>
        <price>2.0</price>
    </good>
</goods>
